
export enum Errors {
  AUTH_TOKEN_INVALID = 'ERROR_INVALID_TOKEN',
  VALIDATION_INVALID_PARAM = 'ERROR_INVALID_PARAM',
  REGISTER_NAME_EXISTS = 'ERROR_NAME_EXISTS',
  REGISTER_EMAIL_EXISTS = 'ERROR_EMAIL_EXISTS',
  REGISTER_DISABLED = 'ERROR_REGISTER_DISABLED',
  REGISTER_INVALID_SERVER_PASSWORD = 'ERROR_REGISTER_INVALID_SERVER_PASSWORD',
  LOGIN_INVALID = 'ERROR_LOGIN_INVALID',
  CLIENT_NOT_CONNECTED = 'CLIENT_NOT_CONNECTED',
  GAME_INVALID_ID = 'ERROR_GAME_INVALID_ID'
};
