
export enum ApiErrorEnum {
  AVATAR_INVALID = 'ERROR_AVATAR_INVALID',
  AUTH_TOKEN_INVALID = 'ERROR_INVALID_TOKEN',
  VALIDATION_INVALID_PARAM = 'ERROR_INVALID_PARAM',
  REGISTER_NAME_EXISTS = 'ERROR_NAME_EXISTS',
  REGISTER_EMAIL_EXISTS = 'ERROR_EMAIL_EXISTS',
  REGISTER_DISABLED = 'ERROR_REGISTER_DISABLED',
  REGISTER_INVALID_SERVER_PASSWORD = 'ERROR_REGISTER_INVALID_SERVER_PASSWORD',
  REQUESTS_LIMIT_REACHED = 'ERROR_REQUESTS_LIMIT_REACHED',
  LOGIN_INVALID = 'ERROR_LOGIN_INVALID',
  GAME_INVALID_ID = 'ERROR_GAME_INVALID_ID',
  PROFILE_INVALID = 'ERROR_PROFILE_INVALID',
  DECK_INVALID = 'ERROR_DECK_INVALID',
  NAME_DUPLICATE = 'ERROR_NAME_DUPLICATE',
  PROMPT_INVALID_ID = 'PROMPT_INVALID_ID',
  PROMPT_INVALID_RESULT = 'PROMPT_INVALID_RESULT',
  REPLAY_INVALID = 'ERROR_REPLAY_INVALID',
  CANNOT_SEND_MESSAGE = 'CANNOT_SEND_MESSAGE',
  CANNOT_READ_MESSAGE = 'CANNOT_READ_MESSAGE',
  CONVERSATION_INVALID = 'CONVERSATION_INVALID',
  UNSUPPORTED_VERSION = 'UNSUPPORTED_VERSION',
  SOCKET_ERROR = 'SOCKET_ERROR'
};
