export enum CardMessage {
  LOG_SHUFFLE_BOTH = 'Both players shuffle the decks.',
  LOG_DRAW_BOTH = 'Both players draw {1} cards.',
  LOG_STARTS_BECAUSE_OVEREAGER = '{1} starts game, because of the Overeager ability.',
  CHOOSE_ONE_POKEMON = 'CHOOSE_ONE_POKEMON',
  CHOOSE_ANY_TWO_CARDS = 'CHOOSE_ANY_TWO_CARDS',
  CHOOSE_ANY_CARD = 'CHOOSE_ANY_CARD',
  CHOOSE_UP_TO_BASIC_POKEMON = 'CHOOSE_UP_TO_BASIC_POKEMON',
  CHOOSE_OPPONENTS_POKEMON = 'CHOOSE_OPPONENTS_POKEMON',
  CARDS_SHOWED_BY_THE_OPPONENT = 'CARDS_SHOWED_BY_THE_OPPONENT',
  COIN_FLIP = 'COIN_FLIP',
  CHOOSE_SUPPORTER_CARD = 'CHOOSE_SUPPORTER_CARD',
  USE_FLASH_BITE_ABILITY = 'USE_FLASH_BITE_ABILITY',
  PLAY_BOTH_CARDS_AT_ONCE = 'PLAY_BOTH_CARDS_AT_ONCE',
  CHOOSE_SP_POKEMON = 'CHOOSE_SP_POKEMON'
}
